//Get all books 
GET  http://localhost:3000/api/books

###

//Get book by id
GET  http://localhost:3000/api/books/2/

###

//Create a new book
POST http://localhost:3000/api/books/
Content-Type: application/json

   {
    "title": "Greenlights",
    "author": "Matthew McConaughey",
    "isbn": "9781472280848",
    "pages": "",
    "published": ""
   }


###

//Update a book
PUT http://localhost:3000/api/books/1
Content-Type: application/json

{
  "title": "pearl harborrrrrr",
    "author": "Roberta Wohlstetter",
    "isbn": "9780804705981",
    "pages": "428",
    "published": "1962"
}

###

//Delete a book
DELETE http://localhost:3000/api/books/2
Content-Type: application/json

