GET  http://localhost:3000/

###

GET  http://localhost:3000/api/books/2/

###

POST http://localhost:3000/api/books/
Content-Type: application/json

   {
    
    "title": "pearl harbor",
    "author": "Roberta Wohlstetter",
    "isbn": "9780804705981",
    "pages": "428",
    "published": "1962"
   }


###

PUT http://localhost:3000/api/books/1
Content-Type: application/json

{
  "title": "pearl harborrrr",
    "author": "Roberta Wohlstetter",
    "isbn": "9780804705981",
    "pages": "428",
    "published": "1962"
}

###
DELETE http://localhost:3000/api/books/1
Content-Type: application/json

